services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"  # 🔁 On redirige maintenant le port local 8888 vers le port 80 du conteneur
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: zoo_db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

